/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import DAO.MedicamentoDAO;
import Model.MedicamentoTableModel;
import Objetos.Medicamento;

/**
 *
 * @author luis.fmleite
 */
public class CadastroMedicamento extends javax.swing.JFrame {

    MedicamentoTableModel modelo = new MedicamentoTableModel();

    /**
     * Creates new form CadastroMedicamento
     */
    public CadastroMedicamento() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTTabelaMed.setModel(modelo);
        modelo.recarregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTQuantidadeMedicamento = new javax.swing.JTextField();
        jTCodigoMedicamento = new javax.swing.JTextField();
        jTDataValidadeMedicamento = new javax.swing.JTextField();
        jTValorMedicamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTNomeMedicamento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTDescricaoMedicamento = new javax.swing.JTextField();
        jBCadastrarMed = new javax.swing.JButton();
        jBVoltarCadastroMedicamento = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTCodigoCatalogo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTabelaMed = new javax.swing.JTable();
        jBExcluirMed = new javax.swing.JButton();
        jBAlterarMed = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO MEDICAMENTO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Código:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Descrição:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Valor:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Data de Validade:");

        jTNomeMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomeMedicamentoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Quantidade:");

        jTDescricaoMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDescricaoMedicamentoActionPerformed(evt);
            }
        });

        jBCadastrarMed.setText("Cadastrar");
        jBCadastrarMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarMedActionPerformed(evt);
            }
        });

        jBVoltarCadastroMedicamento.setText("Voltar");
        jBVoltarCadastroMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarCadastroMedicamentoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Código Catálogo");

        jTTabelaMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTTabelaMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTTabelaMedMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTTabelaMed);

        jBExcluirMed.setText("Excluir");
        jBExcluirMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirMedActionPerformed(evt);
            }
        });

        jBAlterarMed.setText("Alterar");
        jBAlterarMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarMedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBCadastrarMed)
                                .addGap(18, 18, 18)
                                .addComponent(jBExcluirMed)
                                .addGap(26, 26, 26)
                                .addComponent(jBAlterarMed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBVoltarCadastroMedicamento))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTValorMedicamento)
                                    .addComponent(jTQuantidadeMedicamento)
                                    .addComponent(jTDescricaoMedicamento)
                                    .addComponent(jTNomeMedicamento)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTCodigoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTDataValidadeMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTCodigoCatalogo)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTNomeMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTDescricaoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTQuantidadeMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTCodigoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTDataValidadeMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTCodigoCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTValorMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrarMed)
                    .addComponent(jBVoltarCadastroMedicamento)
                    .addComponent(jBExcluirMed)
                    .addComponent(jBAlterarMed))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTDescricaoMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDescricaoMedicamentoActionPerformed

    }//GEN-LAST:event_jTDescricaoMedicamentoActionPerformed

    private void jBCadastrarMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarMedActionPerformed
        Medicamento cmed = new Medicamento();
        MedicamentoDAO dao = new MedicamentoDAO();

        cmed.setNomeMed(jTNomeMedicamento.getText());
        cmed.setDescricaoMed(jTQuantidadeMedicamento.getText());
        cmed.setQuantidadeMed(Integer.parseInt(jTQuantidadeMedicamento.getText()));
        cmed.setCodMed(Integer.parseInt(jTCodigoMedicamento.getText()));
        cmed.setValorMed(Double.valueOf(jTValorMedicamento.getText().replace(",", ".")));
        cmed.setDataValidadeMed(jTDataValidadeMedicamento.getText());
        cmed.setCodCatMed(Integer.parseInt(jTCodigoCatalogo.getText()));

        dao.create(cmed);
        modelo.recarregaTabela();
        LimpaCampos();

    }//GEN-LAST:event_jBCadastrarMedActionPerformed

    private void jTNomeMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomeMedicamentoActionPerformed

    }//GEN-LAST:event_jTNomeMedicamentoActionPerformed

    private void jBVoltarCadastroMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarCadastroMedicamentoActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBVoltarCadastroMedicamentoActionPerformed

    private void jBExcluirMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirMedActionPerformed
        if (jTTabelaMed.getSelectedRow() != -1) {
            Medicamento cmed = modelo.pegaDadosLinha(jTTabelaMed.getSelectedRow());
            MedicamentoDAO dao = new MedicamentoDAO();
            dao.delete(cmed);
            modelo.recarregaTabela();
        }
    }//GEN-LAST:event_jBExcluirMedActionPerformed

    private void jBAlterarMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarMedActionPerformed
        if (jTTabelaMed.getSelectedRow() != -1) {
            modelo.setValueAt(jTCodigoMedicamento.getText(), jTTabelaMed.getSelectedRow(), 0);
            modelo.setValueAt(jTNomeMedicamento.getText(), jTTabelaMed.getSelectedRow(), 1);
            modelo.setValueAt(jTDescricaoMedicamento.getText(), jTTabelaMed.getSelectedRow(), 2);
            modelo.setValueAt(jTQuantidadeMedicamento.getText(), jTTabelaMed.getSelectedRow(), 3);
            modelo.setValueAt(jTValorMedicamento.getText(), jTTabelaMed.getSelectedRow(), 4);
            modelo.setValueAt(jTDataValidadeMedicamento.getText(), jTTabelaMed.getSelectedRow(), 5);
            modelo.setValueAt(jTCodigoCatalogo.getText(), jTTabelaMed.getSelectedRow(), 6);

            Medicamento cmed = modelo.pegaDadosLinha(jTTabelaMed.getSelectedRow());
            MedicamentoDAO dao = new MedicamentoDAO();
            dao.updtae(cmed);
            LimpaCampos();
            modelo.recarregaTabela();
        }
    }//GEN-LAST:event_jBAlterarMedActionPerformed

    private void jTTabelaMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTTabelaMedMouseClicked
        if (jTTabelaMed.getSelectedRow() != -1){
            Medicamento cmed = modelo.pegaDadosLinha(jTTabelaMed.getSelectedRow());
            jTNomeMedicamento.setText(cmed.getNomeMed());
            jTDescricaoMedicamento.setText(cmed.getDescricaoMed());
            jTDataValidadeMedicamento.setText(cmed.getDataValidadeMed());
            jTValorMedicamento.setText(String.valueOf(cmed.getValorMed()));
            jTQuantidadeMedicamento.setText(String.valueOf(cmed.getQuantidadeMed()));
            jTCodigoMedicamento.setText(String.valueOf(cmed.getCodMed()));
            jTCodigoCatalogo.setText(String.valueOf(cmed.getCodCatMed()));
        }
    }//GEN-LAST:event_jTTabelaMedMouseClicked

    private void LimpaCampos() {
        jTCodigoCatalogo.setText("");
        jTCodigoMedicamento.setText("");
        jTDataValidadeMedicamento.setText("");
        jTDescricaoMedicamento.setText("");
        jTNomeMedicamento.setText("");
        jTQuantidadeMedicamento.setText("");
        jTValorMedicamento.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMedicamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterarMed;
    private javax.swing.JButton jBCadastrarMed;
    private javax.swing.JButton jBExcluirMed;
    private javax.swing.JButton jBVoltarCadastroMedicamento;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCodigoCatalogo;
    private javax.swing.JTextField jTCodigoMedicamento;
    private javax.swing.JTextField jTDataValidadeMedicamento;
    private javax.swing.JTextField jTDescricaoMedicamento;
    private javax.swing.JTextField jTNomeMedicamento;
    private javax.swing.JTextField jTQuantidadeMedicamento;
    private javax.swing.JTable jTTabelaMed;
    private javax.swing.JTextField jTValorMedicamento;
    // End of variables declaration//GEN-END:variables
}
