/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import DAO.DrogariaDAO;
import Model.DrogariaTableModel;
import Objetos.DrogariaObjeto;
import java.awt.Color;

/**
 *
 * @author andrey.munhoz
 */
public class Drogaria extends javax.swing.JFrame {
    
        private Menu menu;
        
     DrogariaTableModel modelo = new DrogariaTableModel();

    /**
     * Creates new form Drogaria2
     */
    public Drogaria(Menu menu) {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.menu = menu;
        this.setLocationRelativeTo(null);
        jTTabelaDrogaria.setModel(modelo);
        modelo.recarregaTabela();
        styleComponents();
    }
    
    public Drogaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTEmailDrogaria = new javax.swing.JTextField();
        jBCadastrarDrogaria = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTNumeroDrogaria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTNomeDrogaria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBVoltarDrogaria = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTabelaDrogaria = new javax.swing.JTable();
        jBExcluirDrogaria = new javax.swing.JButton();
        jBAlterarDrogaria = new javax.swing.JButton();
        jTCNPJDrograria = new javax.swing.JFormattedTextField();
        jTCEPDrogaria = new javax.swing.JFormattedTextField();
        jTTelDrogaria = new javax.swing.JFormattedTextField();
        jBDesativados = new javax.swing.JButton();
        jBLimparCampos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jLabel2.setText("Nome:");

        jLabel8.setText("E-mail:");

        jLabel3.setText("CNPJ:");

        jTEmailDrogaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEmailDrogariaActionPerformed(evt);
            }
        });

        jBCadastrarDrogaria.setText("Cadastrar");
        jBCadastrarDrogaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarDrogariaActionPerformed(evt);
            }
        });

        jLabel5.setText("CEP:");

        jLabel6.setText("Número:");

        jLabel7.setText("Telefone:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DROGARIA");

        jBVoltarDrogaria.setText("Voltar");
        jBVoltarDrogaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarDrogariaActionPerformed(evt);
            }
        });

        jTTabelaDrogaria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTTabelaDrogaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTTabelaDrogariaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTTabelaDrogaria);

        jBExcluirDrogaria.setText("Excluir");
        jBExcluirDrogaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirDrogariaActionPerformed(evt);
            }
        });

        jBAlterarDrogaria.setText("Alterar");
        jBAlterarDrogaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarDrogariaActionPerformed(evt);
            }
        });

        try {
            jTCNPJDrograria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTCNPJDrograria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCNPJDrograriaActionPerformed(evt);
            }
        });

        try {
            jTCEPDrogaria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jTTelDrogaria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jBDesativados.setText("Desativados");
        jBDesativados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDesativadosActionPerformed(evt);
            }
        });

        jBLimparCampos.setText("Limpar Campos");
        jBLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpaCampos();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBLimparCampos)
                        .addGap(18, 18, 18)
                        .addComponent(jBDesativados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBAlterarDrogaria)
                        .addGap(18, 18, 18)
                        .addComponent(jBExcluirDrogaria)
                        .addGap(18, 18, 18)
                        .addComponent(jBCadastrarDrogaria)
                        .addGap(18, 18, 18)
                        .addComponent(jBVoltarDrogaria))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jTCNPJDrograria)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTNumeroDrogaria, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTNomeDrogaria))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(801, 928, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTCEPDrogaria, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jTTelDrogaria, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
                            .addComponent(jTEmailDrogaria))))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTNomeDrogaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTEmailDrogaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTCNPJDrograria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTNumeroDrogaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTTelDrogaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCEPDrogaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrarDrogaria)
                    .addComponent(jBVoltarDrogaria)
                    .addComponent(jBExcluirDrogaria)
                    .addComponent(jBAlterarDrogaria)
                    .addComponent(jBDesativados)
                    .addComponent(jBLimparCampos))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarDrogariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarDrogariaActionPerformed
        // Validação de campos obrigatórios
        if (jTNomeDrogaria.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: O campo Nome é obrigatório.", "Erro de Validação", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Validação de CNPJ (formato XX.XXX.XXX/XXXX-XX)
        String cnpj = jTCNPJDrograria.getText().trim();
        if (!cnpj.matches("\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: CNPJ inválido. Preencha no formato XX.XXX.XXX/XXXX-XX.", "Erro de Validação", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Validação de Email
        String email = jTEmailDrogaria.getText().trim();
        if (!email.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: E-mail inválido.", "Erro de Validação", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Validação de Número > 0
        try {
            int numero = Integer.parseInt(jTNumeroDrogaria.getText().trim());
            if (numero <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro: O campo Número deve ser maior que zero.", "Erro de Validação", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: O campo Número deve conter apenas números.", "Erro de Validação", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        DrogariaObjeto d = new DrogariaObjeto();
        DrogariaDAO dao = new DrogariaDAO();
        
        d.setNomeDrogaria(jTNomeDrogaria.getText());
        d.setCnpjDrogaria(jTCNPJDrograria.getText());
        d.setCepDrogaria(jTCEPDrogaria.getText());
        d.setEmailDrogaria(jTEmailDrogaria.getText());
        d.setTelefoneDrogaria(jTTelDrogaria.getText());
        d.setNumeroDrogaria(Integer.parseInt(jTNumeroDrogaria.getText().trim()));
        
        dao.create(d);
        modelo.recarregaTabela();
        LimpaCampos();
        
    }//GEN-LAST:event_jBCadastrarDrogariaActionPerformed

    private void jBVoltarDrogariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarDrogariaActionPerformed
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBVoltarDrogariaActionPerformed

    private void jTEmailDrogariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEmailDrogariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEmailDrogariaActionPerformed

    private void jTTabelaDrogariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTTabelaDrogariaMouseClicked
         if (jTTabelaDrogaria.getSelectedRow() != -1){
           DrogariaObjeto d = modelo.pegaDadosLinha(jTTabelaDrogaria.getSelectedRow());
            jTNomeDrogaria.setText(d.getNomeDrogaria());
            jTCNPJDrograria.setText(d.getCnpjDrogaria());
            jTNumeroDrogaria.setText(String.valueOf(d.getNumeroDrogaria()));
            jTCEPDrogaria.setText(d.getCepDrogaria());
            jTEmailDrogaria.setText(d.getEmailDrogaria());
            jTTelDrogaria.setText(d.getTelefoneDrogaria());
        }
    }//GEN-LAST:event_jTTabelaDrogariaMouseClicked

    private void jBAlterarDrogariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarDrogariaActionPerformed
        if (jTTabelaDrogaria.getSelectedRow() != -1) {
            modelo.setValueAt(jTCNPJDrograria.getText(), jTTabelaDrogaria.getSelectedRow(), 0);
            modelo.setValueAt(jTNomeDrogaria.getText(), jTTabelaDrogaria.getSelectedRow(), 1);
            modelo.setValueAt(jTTelDrogaria.getText(), jTTabelaDrogaria.getSelectedRow(), 2);
            modelo.setValueAt(jTEmailDrogaria.getText(), jTTabelaDrogaria.getSelectedRow(), 3);
            modelo.setValueAt(jTCEPDrogaria.getText(), jTTabelaDrogaria.getSelectedRow(), 4);
            modelo.setValueAt(jTNumeroDrogaria.getText(), jTTabelaDrogaria.getSelectedRow(), 5);

            DrogariaObjeto d = modelo.pegaDadosLinha(jTTabelaDrogaria.getSelectedRow());
            DrogariaDAO dao = new DrogariaDAO();
            dao.update(d);
            LimpaCampos();
            modelo.recarregaTabela();
        }
    }//GEN-LAST:event_jBAlterarDrogariaActionPerformed

    private void jBExcluirDrogariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirDrogariaActionPerformed
        if (jTTabelaDrogaria.getSelectedRow() != -1) {
            DrogariaObjeto d = modelo.pegaDadosLinha(jTTabelaDrogaria.getSelectedRow());
            DrogariaDAO dao = new DrogariaDAO();
            dao.delete(d);
            modelo.recarregaTabela();
        }
    }//GEN-LAST:event_jBExcluirDrogariaActionPerformed

    private void jBDesativadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDesativadosActionPerformed
        Drog_Inativos d = new Drog_Inativos(modelo);
        d.setVisible(true);
    }//GEN-LAST:event_jBDesativadosActionPerformed

    private void jTCNPJDrograriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCNPJDrograriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCNPJDrograriaActionPerformed

    private void styleComponents() {
        getContentPane().setBackground(new Color(30, 30, 30));
        
        // Labels
        javax.swing.JLabel[] labels = {jLabel1, jLabel2, jLabel3, jLabel5, jLabel6, jLabel7, jLabel8};
        for (javax.swing.JLabel lbl : labels) {
            lbl.setForeground(Color.WHITE);
        }
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));

        // TextFields
        javax.swing.JTextField[] fields = {jTNomeDrogaria, jTCNPJDrograria, jTCEPDrogaria, jTEmailDrogaria, jTNumeroDrogaria, jTTelDrogaria};
        for (javax.swing.JTextField fld : fields) {
            fld.setBackground(new Color(60, 60, 60));
            fld.setForeground(Color.WHITE);
            fld.setCaretColor(Color.WHITE);
            fld.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(80, 80, 80)));
        }

        // Buttons
        javax.swing.JButton[] botoes = {jBCadastrarDrogaria, jBAlterarDrogaria, jBExcluirDrogaria, jBDesativados, jBVoltarDrogaria, jBLimparCampos};
                for (javax.swing.JButton btn : botoes) {
            btn.setBackground(new java.awt.Color(45, 45, 45));
            btn.setForeground(java.awt.Color.WHITE);
            btn.setFocusPainted(false);
            btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
            btn.setPreferredSize(new java.awt.Dimension(160, 40));
            btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(70, 70, 70)));
            btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        }
        jBCadastrarDrogaria.setBackground(new Color(0, 100, 0));
        jBAlterarDrogaria.setBackground(new Color(0, 120, 215));
        jBExcluirDrogaria.setBackground(new Color(150, 0, 0));
        jBDesativados.setBackground(new Color(100, 100, 0));

        // Table
        jTTabelaDrogaria.setBackground(new Color(60, 60, 60));
        jTTabelaDrogaria.setForeground(Color.WHITE);
        jTTabelaDrogaria.setGridColor(new Color(80, 80, 80));
        jTTabelaDrogaria.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        jTTabelaDrogaria.setRowHeight(25);
        jTTabelaDrogaria.setSelectionBackground(new Color(0, 100, 0, 80));
        jTTabelaDrogaria.setSelectionForeground(Color.WHITE);
        jTTabelaDrogaria.getTableHeader().setBackground(new Color(30, 30, 30));
        jTTabelaDrogaria.getTableHeader().setForeground(Color.WHITE);
        jTTabelaDrogaria.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        jTTabelaDrogaria.setFillsViewportHeight(true);
        jScrollPane1.getViewport().setBackground(new Color(45, 45, 45));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }

    private void LimpaCampos() {
        jTCEPDrogaria.setText("");
        jTCNPJDrograria.setText("");
        jTEmailDrogaria.setText("");
        jTNomeDrogaria.setText("");
        jTNumeroDrogaria.setText("");
        jTTelDrogaria.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Drogaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Drogaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Drogaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Drogaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Drogaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterarDrogaria;
    private javax.swing.JButton jBCadastrarDrogaria;
    private javax.swing.JButton jBDesativados;
    private javax.swing.JButton jBExcluirDrogaria;
    private javax.swing.JButton jBLimparCampos;
    private javax.swing.JButton jBVoltarDrogaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jTCEPDrogaria;
    private javax.swing.JFormattedTextField jTCNPJDrograria;
    private javax.swing.JTextField jTEmailDrogaria;
    private javax.swing.JTextField jTNomeDrogaria;
    private javax.swing.JTextField jTNumeroDrogaria;
    private javax.swing.JTable jTTabelaDrogaria;
    private javax.swing.JFormattedTextField jTTelDrogaria;
    // End of variables declaration//GEN-END:variables
}
