/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import DAO.DrogariaDAO;
import Model.DrogariaTableModel;
import Objetos.DrogariaObjeto;
import java.awt.Color;

/**
 *
 * @author andrey.munhoz
 */
public class Drogaria extends javax.swing.JFrame {
    
     DrogariaTableModel modelo = new DrogariaTableModel();

    /**
     * Creates new form Drogaria2
     */
    public Drogaria() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTTabelaDrogaria.setModel(modelo);
        modelo.recarregaTabela();
        getContentPane().setBackground(Color.GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTEmailDrogaria = new javax.swing.JTextField();
        jBCadastrarDrogaria = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTCNPJDrograria = new javax.swing.JTextField();
        jTCEPDrogaria = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTNumeroDrogaria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTTelDrogaria = new javax.swing.JTextField();
        jTNomeDrogaria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBVoltarDrogaria = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTabelaDrogaria = new javax.swing.JTable();
        jBExcluirDrogaria = new javax.swing.JButton();
        jBAlterarDrogaria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nome:");

        jLabel8.setText("E-mail:");

        jLabel3.setText("CNPJ:");

        jTEmailDrogaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEmailDrogariaActionPerformed(evt);
            }
        });

        jBCadastrarDrogaria.setText("Cadastrar");
        jBCadastrarDrogaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarDrogariaActionPerformed(evt);
            }
        });

        jLabel5.setText("CEP:");

        jLabel6.setText("Número:");

        jLabel7.setText("Telefone:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DROGARIA");

        jBVoltarDrogaria.setText("Voltar");
        jBVoltarDrogaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarDrogariaActionPerformed(evt);
            }
        });

        jTTabelaDrogaria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTTabelaDrogaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTTabelaDrogariaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTTabelaDrogaria);

        jBExcluirDrogaria.setText("Excluir");
        jBExcluirDrogaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirDrogariaActionPerformed(evt);
            }
        });

        jBAlterarDrogaria.setText("Alterar");
        jBAlterarDrogaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarDrogariaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNomeDrogaria)
                            .addComponent(jTCNPJDrograria)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(31, 31, 31)
                                .addComponent(jTCEPDrogaria, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTEmailDrogaria, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTNumeroDrogaria, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jTTelDrogaria, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBAlterarDrogaria)
                        .addGap(18, 18, 18)
                        .addComponent(jBExcluirDrogaria)
                        .addGap(18, 18, 18)
                        .addComponent(jBCadastrarDrogaria)
                        .addGap(18, 18, 18)
                        .addComponent(jBVoltarDrogaria)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTNomeDrogaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTCNPJDrograria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTCEPDrogaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTNumeroDrogaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTTelDrogaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTEmailDrogaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrarDrogaria)
                    .addComponent(jBVoltarDrogaria)
                    .addComponent(jBExcluirDrogaria)
                    .addComponent(jBAlterarDrogaria))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarDrogariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarDrogariaActionPerformed
        DrogariaObjeto d = new DrogariaObjeto();
        DrogariaDAO dao = new DrogariaDAO();
        
        d.setNomeDrogaria(jTNomeDrogaria.getText());
        d.setCnpjDrogaria(jTCNPJDrograria.getText());
        d.setCepDrogaria(jTCEPDrogaria.getText());
        d.setEmailDrogaria(jTEmailDrogaria.getText());
        d.setTelefoneDrogaria(jTTelDrogaria.getText());
        d.setNumeroDrogaria(Integer.parseInt(jTNumeroDrogaria.getText()));
        
        dao.create(d);
        modelo.recarregaTabela();
        LimpaCampos();
        
    }//GEN-LAST:event_jBCadastrarDrogariaActionPerformed

    private void jBVoltarDrogariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarDrogariaActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBVoltarDrogariaActionPerformed

    private void jTEmailDrogariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEmailDrogariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEmailDrogariaActionPerformed

    private void jTTabelaDrogariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTTabelaDrogariaMouseClicked
         if (jTTabelaDrogaria.getSelectedRow() != -1){
           DrogariaObjeto d = modelo.pegaDadosLinha(jTTabelaDrogaria.getSelectedRow());
            jTNomeDrogaria.setText(d.getNomeDrogaria());
            jTCNPJDrograria.setText(d.getCnpjDrogaria());
            jTNumeroDrogaria.setText(String.valueOf(d.getNumeroDrogaria()));
            jTCEPDrogaria.setText(d.getCepDrogaria());
            jTEmailDrogaria.setText(d.getEmailDrogaria());
            jTTelDrogaria.setText(d.getTelefoneDrogaria());
        }
    }//GEN-LAST:event_jTTabelaDrogariaMouseClicked

    private void jBAlterarDrogariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarDrogariaActionPerformed
        if (jTTabelaDrogaria.getSelectedRow() != -1) {
            modelo.setValueAt(jTCNPJDrograria.getText(), jTTabelaDrogaria.getSelectedRow(), 0);
            modelo.setValueAt(jTNomeDrogaria.getText(), jTTabelaDrogaria.getSelectedRow(), 1);
            modelo.setValueAt(jTTelDrogaria.getText(), jTTabelaDrogaria.getSelectedRow(), 2);
            modelo.setValueAt(jTEmailDrogaria.getText(), jTTabelaDrogaria.getSelectedRow(), 3);
            modelo.setValueAt(jTCEPDrogaria.getText(), jTTabelaDrogaria.getSelectedRow(), 4);
            modelo.setValueAt(jTNumeroDrogaria.getText(), jTTabelaDrogaria.getSelectedRow(), 5);

            DrogariaObjeto d = modelo.pegaDadosLinha(jTTabelaDrogaria.getSelectedRow());
            DrogariaDAO dao = new DrogariaDAO();
            dao.updtae(d);
            LimpaCampos();
            modelo.recarregaTabela();
        }
    }//GEN-LAST:event_jBAlterarDrogariaActionPerformed

    private void jBExcluirDrogariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirDrogariaActionPerformed
        if (jTTabelaDrogaria.getSelectedRow() != -1) {
            DrogariaObjeto d = modelo.pegaDadosLinha(jTTabelaDrogaria.getSelectedRow());
            DrogariaDAO dao = new DrogariaDAO();
            dao.delete(d);
            modelo.recarregaTabela();
        }
    }//GEN-LAST:event_jBExcluirDrogariaActionPerformed

    private void LimpaCampos() {
        jTCEPDrogaria.setText("");
        jTCNPJDrograria.setText("");
        jTEmailDrogaria.setText("");
        jTNomeDrogaria.setText("");
        jTNumeroDrogaria.setText("");
        jTTelDrogaria.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Drogaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Drogaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Drogaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Drogaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Drogaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterarDrogaria;
    private javax.swing.JButton jBCadastrarDrogaria;
    private javax.swing.JButton jBExcluirDrogaria;
    private javax.swing.JButton jBVoltarDrogaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCEPDrogaria;
    private javax.swing.JTextField jTCNPJDrograria;
    private javax.swing.JTextField jTEmailDrogaria;
    private javax.swing.JTextField jTNomeDrogaria;
    private javax.swing.JTextField jTNumeroDrogaria;
    private javax.swing.JTable jTTabelaDrogaria;
    private javax.swing.JTextField jTTelDrogaria;
    // End of variables declaration//GEN-END:variables
}
