/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import DAO.DrogariaDAO;
import DAO.VendaDAO;
import Model.VendaTableModel;
import Objetos.DrogariaObjeto;
import Objetos.Funcionario;
import Objetos.Venda;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author andrey.munhoz
 */
public class JanelaVenda extends javax.swing.JFrame {

    private Funcionario user;
    private String cpf;
    private List<DrogariaObjeto> drogarias = new ArrayList<>();
    private String cnpj;
    VendaTableModel modelo = new VendaTableModel();

    /**
     * Creates new form Compra2
     */
    public JanelaVenda() {
        initComponents();

    }

    public JanelaVenda(Funcionario user) {
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.GRAY);
        this.user = user;
        this.cpf = user.getCpf();
        carregarLaboratorios();
        jBCadastrarVenda.setEnabled(true);
        jTTabelaMed.setModel(modelo);
        modelo.recarregaTabela();

    }

    private void carregarLaboratorios() {
        try {

            DrogariaDAO drogDAO = new DrogariaDAO();

            drogarias = drogDAO.read();
            System.out.println(drogarias.size());
            jCFiltroDrogaria.removeAllItems();
            jCFiltroDrogaria.addItem("Todos");  // Primeiro item

            for (DrogariaObjeto lab : drogarias) {
                jCFiltroDrogaria.addItem(lab.getNomeDrogaria());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Erro ao carregar laboratórios:\n" + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            //   e.printStackTrace();
        }
        jCFiltroDrogaria.setSelectedIndex(0);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jBCadastrarVenda = new javax.swing.JButton();
        jBVoltarCompra = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTTabelaMed = new javax.swing.JTable();
        jCFiltroDrogaria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VENDAS");

        jBCadastrarVenda.setText("Iniciar Venda");
        jBCadastrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarVendaActionPerformed(evt);
            }
        });

        jBVoltarCompra.setText("Voltar");
        jBVoltarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarCompraActionPerformed(evt);
            }
        });

        jTTabelaMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTTabelaMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTTabelaMedMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTTabelaMed);

        jCFiltroDrogaria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCFiltroDrogaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCFiltroDrogariaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Filtro:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(104, 104, 104))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBCadastrarVenda)
                        .addGap(18, 18, 18)
                        .addComponent(jBVoltarCompra)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCFiltroDrogaria, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCFiltroDrogaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrarVenda)
                    .addComponent(jBVoltarCompra))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarVendaActionPerformed
        iniciarCompra();
    }//GEN-LAST:event_jBCadastrarVendaActionPerformed

    private void jBVoltarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarCompraActionPerformed
        Menu m = new Menu(user);
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBVoltarCompraActionPerformed

    private void jTTabelaMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTTabelaMedMouseClicked
    int linhaSelecionada = jTTabelaMed.getSelectedRow();

    if (linhaSelecionada == -1) {
        return;
    }

    // Recupera o objeto Venda direto do TableModel
    Venda vendaSelecionada = modelo.pegaDadosLinha(linhaSelecionada);

    int notaFiscal = vendaSelecionada.getNotaFiscalVenda();

    // Abre a janela de detalhes
    JanelaDetalhesVenda detalhes = new JanelaDetalhesVenda(notaFiscal);
    detalhes.setVisible(true);
    }//GEN-LAST:event_jTTabelaMedMouseClicked

    private void jCFiltroDrogariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCFiltroDrogariaActionPerformed
    int index = jCFiltroDrogaria.getSelectedIndex();

    VendaDAO dao = new VendaDAO();

    // Item "Todos"
    if (index <= 0) {
        modelo.setVendas(dao.read());
        return;
    }

    // Ajuste do índice por causa do item "Todos"
    String cnpjSelecionado = drogarias.get(index - 1).getCnpjDrogaria();

    List<Venda> filtradas = new ArrayList<>();

    for (Venda v : dao.read()) {
        if (cnpjSelecionado != null && cnpjSelecionado.equals(v.getCnpjVenda())) {
            filtradas.add(v);
        }
    }

    modelo.setVendas(filtradas);
    }//GEN-LAST:event_jCFiltroDrogariaActionPerformed
    private void iniciarCompra() {
        // Validação: garante que há um funcionário logado
        if (cpf == null || cpf.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Erro: Nenhum funcionário identificado no sistema!\n"
                    + "Por favor, faça login novamente.",
                    "Erro de Autenticação",
                    JOptionPane.ERROR_MESSAGE);

            //redirecionar para tela de login
            new TelaLoginFuncionario().setVisible(true);
            this.dispose();
            return;
        }
        try {
            Venda vendas = new Venda();
            vendas.setValorVenda(0.0);
            vendas.setCpfVenda(cpf); // CPF do funcionário logado
            vendas.setCnpjVenda(null); // será definido ao selecionar a drogaria

            VendaDAO vendaDAO = new VendaDAO();
            int notaGerada = vendaDAO.createAndReturnNota(vendas);

            System.out.println("Venda iniciada - Nota: " + notaGerada
                    + ", Funcionário CPF: " + cpf);

            JOptionPane.showMessageDialog(this,
                    "Venda iniciada com sucesso!\nNota Fiscal: " + notaGerada,
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);

            // Abre a tela de nova venda
            NovaJanelaVenda janela = new NovaJanelaVenda(user, notaGerada, cpf, cnpj);
            janela.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro inesperado ao iniciar venda:\n" + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarVenda;
    private javax.swing.JButton jBVoltarCompra;
    private javax.swing.JComboBox<String> jCFiltroDrogaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTTabelaMed;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
