/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import DAO.CompraDAO;
import Objetos.Compra;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author andrey.munhoz
 */
public class JanelaCompra extends javax.swing.JFrame {
    
        private String cpf;


    
    /**
     * Creates new form Compra2
     */
    public JanelaCompra() {
        initComponents();
        
    }
    public JanelaCompra(String cpf) {
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.GRAY);
        
        this.cpf = cpf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jBCadastrarCompra = new javax.swing.JButton();
        jBVoltarCompra = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTTabelaMed = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COMPRAS");

        jBCadastrarCompra.setText("Iniciar compra");
        jBCadastrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarCompraActionPerformed(evt);
            }
        });

        jBVoltarCompra.setText("Voltar");
        jBVoltarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarCompraActionPerformed(evt);
            }
        });

        jTTabelaMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTTabelaMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTTabelaMedMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTTabelaMed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCadastrarCompra)
                .addGap(18, 18, 18)
                .addComponent(jBVoltarCompra)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrarCompra)
                    .addComponent(jBVoltarCompra))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarCompraActionPerformed
  
    }//GEN-LAST:event_jBCadastrarCompraActionPerformed

    private void jBVoltarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarCompraActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBVoltarCompraActionPerformed

    private void jTTabelaMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTTabelaMedMouseClicked
        
    }//GEN-LAST:event_jTTabelaMedMouseClicked
private void iniciarCompra() {
    // Validação: garante que há um funcionário logado
    if (cpf == null || cpf.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Erro: Nenhum funcionário identificado no sistema!\n" +
            "Por favor, faça login novamente.",
            "Erro de Autenticação",
            JOptionPane.ERROR_MESSAGE);
        
        //redirecionar para tela de login
        new TelaLoginFuncionario().setVisible(true);
        this.dispose();
        return;
    }
    
    
    try {
        Compra compra = new Compra();
        compra.setValorTotal(0.0);
        compra.setCpfCompra(cpf); // CPF do funcionário logado
        compra.setCnpjCompra(null); // será definido ao selecionar a drogaria
        
        CompraDAO compraDAO = new CompraDAO();
        int notaGerada = compraDAO.createAndReturnNota(compra);
        
        
        System.out.println("Compra iniciada - Nota: " + notaGerada + 
                         ", Funcionário CPF: " + cpf);
        
        JOptionPane.showMessageDialog(this,
            "Compra iniciada com sucesso!\nNota Fiscal: " + notaGerada,
            "Sucesso",
            JOptionPane.INFORMATION_MESSAGE);
        
        // Abre a tela de nova compra
        NovaJanelaCompra janela = new NovaJanelaCompra(notaGerada, cpf);
        janela.setVisible(true);
        this.dispose();
        
    } 
        
     catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Erro inesperado ao iniciar compra:\n" + e.getMessage(),
            "Erro",
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarCompra;
    private javax.swing.JButton jBVoltarCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTTabelaMed;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
