/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import DAO.DrogariaDAO;
import DAO.ItensVendaDAO;
import DAO.MedicamentoDAO;
import DAO.VendaDAO;
import Model.ItensVendaTableModel;
import Model.MedicamentoTableModel;
import Objetos.DrogariaObjeto;
import Objetos.Funcionario;
import Objetos.ItensVenda;
import Objetos.Venda;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author luis.fmleite
 */
public class NovaJanelaVenda extends javax.swing.JFrame {

    private Funcionario user;
    private String cpf;
    private List<DrogariaObjeto> drogarias = new ArrayList<>();
    private String cnpjDrogaria;
    private int notaFiscalVenda;
    private double valorTotalVenda = 0.0;
    ItensVendaTableModel modeloItem = new ItensVendaTableModel();
    MedicamentoTableModel modeloMed = new MedicamentoTableModel();
        private Menu menu;

    /**
     * Creates new form NovaJanelaCompra
     */
    public NovaJanelaVenda() {
        initComponents();
    }

    public NovaJanelaVenda(Funcionario user, int notaGerada, String cpf, String cnpj, Menu menu) {
        initComponents();
        this.user = user;
        carregarDrogarias();
        this.menu = menu;

        jBFinalizarNovaCompra.setEnabled(false);

        this.cpf = user.getCpf();
        this.notaFiscalVenda = notaGerada;
        modeloMed.recarregaTabela();
        jTTabelaNovaCompra.setModel(modeloMed);
        jTTabelaItensCompra.setModel(modeloItem);
        atualizarValorTotal();

        getContentPane().setBackground(Color.GRAY);
        jCDrogarias.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int index = jCDrogarias.getSelectedIndex();

                if (index == 0) {
                    cnpjDrogaria = null;
                    jBFinalizarNovaCompra.setEnabled(false);
                    return;
                }

                // Seleção válida
                cnpjDrogaria = drogarias.get(jCDrogarias.getSelectedIndex()).getCnpjDrogaria();
                System.out.println("Drogaria selecionada: " + cnpjDrogaria);
                jBFinalizarNovaCompra.setEnabled(true);
            }
        });
    }
// Método para calcular o valor total da compra

    private void carregarDrogarias() {
        try {
            DrogariaDAO drogDAO = new DrogariaDAO();
            drogarias = drogDAO.read();

            jCDrogarias.removeAllItems();
            jCDrogarias.addItem("-- Selecione uma drogaria --");

            for (DrogariaObjeto d : drogarias) {
                jCDrogarias.addItem(d.getNomeDrogaria());
            }

            jCDrogarias.setSelectedIndex(0);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar drogarias:\n" + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private double calcularValorTotal() {
        double total = 0.0;

        // Percorre todos os itens da tabela
        for (int i = 0; i < modeloItem.getRowCount(); i++) {
            ItensVenda itemVenda = modeloItem.pegaDadosLinha(i);
            double valorItem = itemVenda.getValorItemVenda() * itemVenda.getQuantidadeItemVenda();
            total += valorItem;
        }

        return total;
    }

    // Método para atualizar a exibição do valor total
    private void atualizarValorTotal() {
        valorTotalVenda = calcularValorTotal();
        jLabel5.setText(String.format("Itens da compra - Total: R$ %.2f", valorTotalVenda));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBFinalizarNovaCompra = new javax.swing.JButton();
        jBCancelarNovaCompra = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTTabelaNovaCompra = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTTabelaItensCompra = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCDrogarias = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nova Venda");

        jBFinalizarNovaCompra.setText("Finalizar");
        jBFinalizarNovaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinalizarNovaCompraActionPerformed(evt);
            }
        });

        jBCancelarNovaCompra.setText("Cancelar");
        jBCancelarNovaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarNovaCompraActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setText("Itens da venda");

        jTTabelaNovaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTTabelaNovaCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTTabelaNovaCompraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTTabelaNovaCompra);

        jTTabelaItensCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTTabelaItensCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTTabelaItensCompraMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTTabelaItensCompra);

        jLabel2.setText("Total:");

        jLabel5.setText("Total:");

        jCDrogarias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCDrogarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCDrogariasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 858, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBFinalizarNovaCompra)
                                .addGap(18, 18, 18)
                                .addComponent(jBCancelarNovaCompra)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jCDrogarias, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1236, 1236, 1236))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(103, 103, 103)
                .addComponent(jCDrogarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBFinalizarNovaCompra)
                    .addComponent(jBCancelarNovaCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBFinalizarNovaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinalizarNovaCompraActionPerformed
// Validar se selecionou laboratório
        int index = jCDrogarias.getSelectedIndex();

        // Validar se tem itens
        if (modeloItem.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Adicione pelo menos um item antes de finalizar!",
                    "Validação",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (cnpjDrogaria == null || cnpjDrogaria.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Selecione uma drogaria antes de finalizar a venda!",
                    "Validação",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        atualizarValorTotal();
        int confirma = JOptionPane.showConfirmDialog(this,
                String.format("Finalizar a venda?\n"
                        + "Nota Fiscal: %d\n"
                        + "Total de itens: %d\n"
                        + "Valor Total: R$ %.2f",
                        notaFiscalVenda,
                        modeloItem.getRowCount(),
                        valorTotalVenda),
                "Confirmar Venda",
                JOptionPane.YES_NO_OPTION);

        if (confirma == JOptionPane.YES_OPTION) {
            try {
                DrogariaObjeto drogariaSelecionada = drogarias.get(index);
                cnpjDrogaria = drogariaSelecionada.getCnpjDrogaria();
                System.out.println(cnpjDrogaria);
                VendaDAO vendaDAO = new VendaDAO();
                ItensVendaDAO itensDAO = new ItensVendaDAO();
                MedicamentoDAO medDAO = new MedicamentoDAO();

                // Atualiza o valor total da compra no banco
                vendaDAO.atualizarValorTotal(notaFiscalVenda, valorTotalVenda);
                vendaDAO.atualizarCnpj(notaFiscalVenda, cnpjDrogaria);

                // Salvar todos os itens da compra
                for (int i = 0; i < modeloItem.getRowCount(); i++) {
                    ItensVenda itemVenda = modeloItem.pegaDadosLinha(i);

                    // Garante que o item tem a nota fiscal correta
                    itemVenda.setNotaFiscalVendaItem(notaFiscalVenda);

                    // Salva o item no banco
                    itensDAO.create(itemVenda);
                }

                JOptionPane.showMessageDialog(this,
                        String.format("Venda finalizada com sucesso!\n"
                                + "Nota Fiscal: %d\n"
                                + "Total de itens: %d\n"
                                + "Valor Total: R$ %.2f",
                                notaFiscalVenda,
                                modeloItem.getRowCount(),
                                valorTotalVenda),
                        "Sucesso",
                        JOptionPane.INFORMATION_MESSAGE);

                JanelaVenda vmed = new JanelaVenda(user, menu);
                vmed.setVisible(true);
                dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Erro ao finalizar venda: " + e.getMessage(),
                        "Erro",
                        JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_jBFinalizarNovaCompraActionPerformed

    private void jTTabelaNovaCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTTabelaNovaCompraMouseClicked
        //    QUANDO SELECIONA ITEM NA TABELA DE MEDICAMNENTO, MOSTRA PARA INSERIR QUANTIDADE
        // PRECISO PEGAR OS DADOS DO MEDICAMENTO QUE É UM ITEM DA COMPRA, 
        // ADICIONAR NO ATRIBUTO DO ITEM A QUANTIDADE E ADICIONAR NO MODEL DA TABELA DE ITEM;
        if (jTTabelaNovaCompra.getSelectedRow() != -1) {

            int linhaSelecionada = jTTabelaNovaCompra.getSelectedRow();

            // Medicamento selecionado
            var medicamento = modeloMed.pegaDadosLinha(linhaSelecionada);

            int estoqueDisponivel = medicamento.getQuantidadeMed();

            String input = JOptionPane.showInputDialog(
                    this,
                    "Quantidade do Medicamento\nEstoque disponível: " + estoqueDisponivel
            );
            // Cancelou o input
            if (input == null) {
                return;
            }
            int QTD_Item;
            try {
                QTD_Item = Integer.parseInt(input);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(
                        this,
                        "Digite um número válido.",
                        "Erro",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            // Quantidade inválida
            if (QTD_Item <= 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "A quantidade deve ser maior que zero.",
                        "Erro",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            // Quantidade maior que o estoque
            if (QTD_Item > estoqueDisponivel) {
                JOptionPane.showMessageDialog(
                        this,
                        "Quantidade solicitada maior que o estoque disponível.\n"
                        + "Estoque atual: " + estoqueDisponivel,
                        "Estoque insuficiente",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            // PASSOU NA VALIDAÇÃO → adiciona item
            ItensVenda itemVenda = new ItensVenda();
            itemVenda.setDataValItemVenda(medicamento.getDataValidadeMed());
            itemVenda.setValorItemVenda(medicamento.getValorMed());
            itemVenda.setCodMedItemVenda(medicamento.getCodMed());
            itemVenda.setQuantidadeItemVenda(QTD_Item);

            modeloItem.addItem(itemVenda);
            atualizarValorTotal();

        }


    }//GEN-LAST:event_jTTabelaNovaCompraMouseClicked

    private void jTTabelaItensCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTTabelaItensCompraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTabelaItensCompraMouseClicked

    private void jBCancelarNovaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarNovaCompraActionPerformed
        int confirma = JOptionPane.showConfirmDialog(this,
                "Deseja realmente cancelar esta venda?\nTodos os itens adicionados serão perdidos!",
                "Confirmar Cancelamento",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirma == JOptionPane.YES_OPTION) {
            //EXCLUI A VENDA NO BANCO
            Venda v = new Venda();
            v.setNotaFiscalVenda(notaFiscalVenda);

            VendaDAO dao = new VendaDAO();
            dao.delete(v);
            JanelaVenda vmed = new JanelaVenda(user, menu);
            vmed.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jBCancelarNovaCompraActionPerformed

    private void jCDrogariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCDrogariasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCDrogariasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaJanelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaJanelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaJanelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaJanelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaJanelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelarNovaCompra;
    private javax.swing.JButton jBFinalizarNovaCompra;
    private javax.swing.JComboBox<String> jCDrogarias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTTabelaItensCompra;
    private javax.swing.JTable jTTabelaNovaCompra;
    // End of variables declaration//GEN-END:variables

}
