/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import DAO.LaboratorioDAO;
import Model.ItensTableModel;
import Objetos.Laboratorio;
import java.awt.Color;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author luis.fmleite
 */

public class NovaJanelaCompra extends javax.swing.JFrame {
    private int notaFiscalCompra;
    private String cpfFuncionario;
    ItensTableModel modelo = new ItensTableModel();
    /**
     * Creates new form NovaJanelaCompra
     */
    public NovaJanelaCompra() {
        initComponents();
    }

    public NovaJanelaCompra(int notaGerada, String cpf) {
        initComponents();
        this.notaFiscalCompra = notaGerada;
        this.cpfFuncionario = cpf;
        jTTabelaNovaCompra.setModel(modelo);
        modelo.recarregaTabela();
        getContentPane().setBackground(Color.GRAY);
        carregarLaboratorios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBAdicionar = new javax.swing.JButton();
        jCItemNovaCompra = new javax.swing.JComboBox<>();
        jBFinalizarNovaCompra = new javax.swing.JButton();
        jBCancelarNovaCompra = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTDataNovaCompra = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTabelaNovaCompra = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nova Compra");

        jLabel2.setText("Cliente:");

        jLabel3.setText("Data:");

        jBAdicionar.setText("Adicionar");
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });

        jCItemNovaCompra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBFinalizarNovaCompra.setText("Finalizar");
        jBFinalizarNovaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinalizarNovaCompraActionPerformed(evt);
            }
        });

        jBCancelarNovaCompra.setText("Cancelar");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setText("Itens");

        jTextField1.setText("jTextField1");

        try {
            jTDataNovaCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTTabelaNovaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTTabelaNovaCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTTabelaNovaCompraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTTabelaNovaCompra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBFinalizarNovaCompra)
                        .addGap(18, 18, 18)
                        .addComponent(jBCancelarNovaCompra))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTDataNovaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCItemNovaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jBAdicionar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jCItemNovaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jTDataNovaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(46, 46, 46)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBFinalizarNovaCompra)
                                .addComponent(jBCancelarNovaCompra))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(39, 39, 39)
                        .addComponent(jBAdicionar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed
        // Se ainda não existe nota fiscal, cria agora
    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void jBFinalizarNovaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinalizarNovaCompraActionPerformed
// Validar se selecionou laboratório
        Laboratorio labSelecionado = (Laboratorio) jCItemNovaCompra.getSelectedItem();

        if (labSelecionado == null
                || labSelecionado.getCnpjLab() == null
                || labSelecionado.getCnpjLab().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um laboratório antes de finalizar!",
                    "Validação",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar se tem itens
        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Adicione pelo menos um item antes de finalizar!",
                    "Validação",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirma = JOptionPane.showConfirmDialog(this,
                "Finalizar a compra?\nLaboratório: " + labSelecionado.getNomeLab()
                + "\nTotal de itens: " + modelo.getRowCount(),
                "Confirmar",
                JOptionPane.YES_NO_OPTION);

        if (confirma == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this,
                    "Compra finalizada com sucesso!",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    
    }//GEN-LAST:event_jBFinalizarNovaCompraActionPerformed
private void carregarLaboratorios() {
    try {
        LaboratorioDAO labDAO = new LaboratorioDAO();
        List<Laboratorio> laboratorios = labDAO.read();

        // Cria um item vazio para o início
        Laboratorio itemVazio = new Laboratorio();
        itemVazio.setCnpjLab("");
        itemVazio.setNomeLab("");

        // Cria o modelo do ComboBox
        DefaultComboBoxModel<Laboratorio> model = new DefaultComboBoxModel<>();
        model.addElement(itemVazio);

        // Adiciona todos os laboratórios
        for (Laboratorio lab : laboratorios) {
            model.addElement(lab);
        }

        // FAZ O CAST AQUI
        jCItemNovaCompra.setModel((DefaultComboBoxModel) model);
        jCItemNovaCompra.setSelectedIndex(0);

        System.out.println("Laboratórios carregados: " + laboratorios.size());

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,
                "Erro ao carregar laboratórios:\n" + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
    private void jTTabelaNovaCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTTabelaNovaCompraMouseClicked

    }//GEN-LAST:event_jTTabelaNovaCompraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(NovaJanelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(NovaJanelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(NovaJanelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(NovaJanelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new NovaJanelaCompra().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBCancelarNovaCompra;
    private javax.swing.JButton jBFinalizarNovaCompra;
    private javax.swing.JComboBox<String> jCItemNovaCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jTDataNovaCompra;
    private javax.swing.JTable jTTabelaNovaCompra;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
