/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;
import DAO.FuncionarioDAO;
import Objetos.Funcionario;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author lucas.gmpedro
 */
public class TelaCadastroFun extends javax.swing.JFrame {
   
    private final DefaultTableModel modelo;
     
    public TelaCadastroFun() {
        initComponents();
        
        jBoxFun.removeAllItems();    
        jBoxFun.addItem("Gerente");
        jBoxFun.addItem("Funcionário");  
        
        modelo = new DefaultTableModel(
            new Object[][]{},
            new String[]{"Nome", "CPF", "Telefone", "E-mail", "Função"}
        );
        jTTable1.setModel(modelo);
        
        
        carregarTabelaFuncionarios();
        
         // Ao clicar na tabela, preenche os campos automaticamente
        jTTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int linhaSelecionada = jTTable1.getSelectedRow();
                if (linhaSelecionada != -1) {
                    try {
                        // Pega o CPF da linha selecionada
                        String cpf = modelo.getValueAt(linhaSelecionada, 1).toString();

                        // Busca o funcionário completo no banco pelo CPF
                        FuncionarioDAO dao = new FuncionarioDAO();
                        java.util.List<Funcionario> funcionarios = dao.read();

                        for (Funcionario f : funcionarios) {
                            if (f.getCpf().equals(cpf)) {
                                // Preenche TODOS os campos
                                jTNomeFun.setText(f.getNome_Fun());
                                jTCPF.setText(f.getCpf());
                                jTTelefone.setText(f.getTelefone_Fun());
                                jTEmailFun.setText(f.getEmail_Fun());
                                jTCepFun.setText(f.getCep_Fun());
                                jTNumeroFun.setText(String.valueOf(f.getNumero_Fun()));

                                // Função pode ser null nos dados antigos
                                if (f.getFuncao() != null && !f.getFuncao().isEmpty()) {
                                    jBoxFun.setSelectedItem(f.getFuncao());
                                } else {
                                    jBoxFun.setSelectedIndex(0);
                                }

                                jTSenha.setText(""); // Senha vazia por segurança

                                System.out.println("✓ Dados carregados para: " + f.getNome_Fun());

                                // ADICIONADO AQUI ↓↓↓
                                // Desabilita CONFIRMAR e destaca ATUALIZAR quando seleciona uma linha
                                jBConfirmar.setEnabled(false);
                                jBAtualizar.setEnabled(true);

                                break;
                            }
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Erro ao carregar dados: " + e.getMessage());
                        e.printStackTrace();
                    }
                }
            }
        });
        // ESTILIZAÇÃO DO BOTÃO X - Fica vermelho ao passar o mouse
        jBlimpar.setBackground(new java.awt.Color(240, 240, 240));
        jBlimpar.setForeground(java.awt.Color.BLACK);
        jBlimpar.setFocusPainted(false);
        jBlimpar.setBorderPainted(false);

        jBlimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBlimpar.setBackground(new java.awt.Color(220, 53, 69)); // Vermelho
                jBlimpar.setForeground(java.awt.Color.BLACK);
                jBlimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBlimpar.setBackground(new java.awt.Color(240, 240, 240)); // Cinza
                jBlimpar.setForeground(java.awt.Color.BLACK);
                jBlimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            }
        });

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTNomeFun = new javax.swing.JTextField();
        jTCPF = new javax.swing.JTextField();
        jTCepFun = new javax.swing.JTextField();
        jTNumeroFun = new javax.swing.JTextField();
        jTTelefone = new javax.swing.JTextField();
        jTSenha = new javax.swing.JTextField();
        jBoxFun = new javax.swing.JComboBox<>();
        jTEmailFun = new javax.swing.JTextField();
        jBConfirmar = new javax.swing.JButton();
        jBAtualizar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTable1 = new javax.swing.JTable();
        jBlimpar = new javax.swing.JButton();
        jBvoltar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE FUNCIONÁRIO");

        jLabel2.setText("Nome:");

        jLabel3.setText("CPF:");

        jLabel4.setText("Número:");

        jLabel5.setText("CEP:");

        jLabel6.setText("Telefone:");

        jLabel7.setText("Senha:");

        jLabel8.setText("Email:");

        jLabel9.setText("Função:");

        jTNomeFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomeFunActionPerformed(evt);
            }
        });

        jTSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTSenhaActionPerformed(evt);
            }
        });

        jBoxFun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jBoxFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxFunActionPerformed(evt);
            }
        });

        jBConfirmar.setText("CONFIRMAR");
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });

        jBAtualizar.setText("ATUALIZAR");
        jBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarActionPerformed(evt);
            }
        });

        jBExcluir.setText("EXCLUIR");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jTTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jBlimpar.setText("X");
        jBlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimparActionPerformed(evt);
            }
        });

        jBvoltar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jBvoltar.setText("<");
        jBvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(18, 18, 18)
                                    .addComponent(jTNomeFun, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jBConfirmar)
                                        .addGap(60, 60, 60)
                                        .addComponent(jBAtualizar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBExcluir))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBoxFun, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTTelefone))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTNumeroFun, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTCepFun))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTSenha)
                                            .addComponent(jTEmailFun))))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jBlimpar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jBvoltar)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBvoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTNomeFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTCepFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNumeroFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTTelefone)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTSenha))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTEmailFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBoxFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConfirmar)
                    .addComponent(jBAtualizar)
                    .addComponent(jBExcluir))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNomeFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomeFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNomeFunActionPerformed

    private void jTSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTSenhaActionPerformed

    private void jBoxFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxFunActionPerformed
   
    }//GEN-LAST:event_jBoxFunActionPerformed

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        // 1. CAPTURA DOS DADOS
        String nome = jTNomeFun.getText();
        String cpf = jTCPF.getText();
        String telefone = jTTelefone.getText();
        String email = jTEmailFun.getText();
        String funcao = (String) jBoxFun.getSelectedItem();
        String numero = jTNumeroFun.getText();
        String cep = jTCepFun.getText();
        String senhaDigitada = jTSenha.getText();

        // 2. VALIDAÇÃO
        if (nome.isEmpty() || cpf.isEmpty() || telefone.isEmpty() || email.isEmpty()
                || numero.isEmpty() || cep.isEmpty() || senhaDigitada.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos antes de confirmar!");
            return;
        }

        // 3. CONVERSÃO PARA INT DO NÚMERO
        int numeroInt;
        try {
            numeroInt = Integer.parseInt(numero);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Número inválido! Digite apenas números.");
            return;
        }

        // 4. CRIA OBJETO FUNCIONARIO
        Funcionario f = new Funcionario();
        f.setNome_Fun(nome);
        f.setCpf(cpf);
        f.setTelefone_Fun(telefone);
        f.setEmail_Fun(email);
        f.setCep_Fun(cep);
        f.setNumero_Fun(numeroInt);
        f.setSenha(senhaDigitada);
        f.setFuncao(funcao);

        // 5. SALVA NO BANCO
        try {
            FuncionarioDAO dao = new FuncionarioDAO();
            dao.salvar(f);

            // 6. MENSAGEM DE SUCESSO
            JOptionPane.showMessageDialog(this, "Funcionário cadastrado com sucesso!");

            // 7. RECARREGA A TABELA DO BANCO
            carregarTabelaFuncionarios();

            // 8. LIMPAR CAMPOS
            jTNomeFun.setText("");
            jTCPF.setText("");
            jTTelefone.setText("");
            jTEmailFun.setText("");
            jTSenha.setText("");
            jTCepFun.setText("");
            jTNumeroFun.setText("");
            jBoxFun.setSelectedIndex(-1);

            // 9. MANTÉM CONFIRMAR HABILITADO
            jBConfirmar.setEnabled(true);

        } catch (Exception e) {
            // Verifica se é erro de CPF duplicado
            if (e.getMessage() != null && (e.getMessage().contains("Duplicate entry") || e.getMessage().contains("PRIMARY"))) {
                JOptionPane.showMessageDialog(this,
                        "ERRO: Já existe um funcionário cadastrado com este CPF!\n\n"
                        + "Se você deseja ATUALIZAR este funcionário, clique no botão 'ATUALIZAR'.",
                        "CPF Duplicado",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Erro ao cadastrar: " + e.getMessage(),
                        "Erro",
                        JOptionPane.ERROR_MESSAGE);
            }
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConfirmarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        int linhaSelecionada = jTTable1.getSelectedRow();
    
    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um funcionário para excluir.");
    } else {
        int confirmacao = JOptionPane.showConfirmDialog(this,
                "Tem certeza que deseja excluir este funcionário?", "Confirmação", JOptionPane.YES_NO_OPTION);
        
        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                // Pega o CPF da linha selecionada
                String cpf = modelo.getValueAt(linhaSelecionada, 1).toString();
                
                // Cria objeto funcionário com o CPF
                Funcionario f = new Funcionario();
                f.setCpf(cpf);
                
                // Deleta do banco
                FuncionarioDAO dao = new FuncionarioDAO();
                dao.delete(f);
                
                // Mensagem de sucesso
                JOptionPane.showMessageDialog(this, "Funcionário excluído com sucesso!");
                
                // RECARREGA A TABELA
                carregarTabelaFuncionarios();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }

    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed
        // 1. CAPTURA DOS DADOS
        String nome = jTNomeFun.getText();
        String cpf = jTCPF.getText();
        String telefone = jTTelefone.getText();
        String email = jTEmailFun.getText();
        String funcao = (String) jBoxFun.getSelectedItem();
        String numero = jTNumeroFun.getText();
        String cep = jTCepFun.getText();
        String senhaDigitada = jTSenha.getText();

        // 2. VALIDAÇÃO
        if (nome.isEmpty() || cpf.isEmpty() || telefone.isEmpty() || email.isEmpty()
                || numero.isEmpty() || cep.isEmpty() || senhaDigitada.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos antes de atualizar!");
            return;
        }

        // 3. CONVERSÃO PARA INT DO NÚMERO
        int numeroInt;
        try {
            numeroInt = Integer.parseInt(numero);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Número inválido! Digite apenas números.");
            return;
        }

        // 4. CRIA OBJETO FUNCIONARIO COM OS DADOS ATUALIZADOS
        Funcionario f = new Funcionario();
        f.setNome_Fun(nome);
        f.setCpf(cpf);
        f.setTelefone_Fun(telefone);
        f.setEmail_Fun(email);
        f.setCep_Fun(cep);
        f.setNumero_Fun(numeroInt);
        f.setSenha(senhaDigitada); // criptografa automaticamente
        f.setFuncao(funcao);

        // 5. ATUALIZA NO BANCO
        try {
            FuncionarioDAO dao = new FuncionarioDAO();
            dao.update(f);

            // 6. MENSAGEM DE SUCESSO
            JOptionPane.showMessageDialog(this, "Funcionário atualizado com sucesso!");

            // 7. RECARREGA A TABELA DO BANCO
            carregarTabelaFuncionarios();

            // 8. LIMPAR CAMPOS
            jTNomeFun.setText("");
            jTCPF.setText("");
            jTTelefone.setText("");
            jTEmailFun.setText("");
            jTSenha.setText("");
            jTCepFun.setText("");
            jTNumeroFun.setText("");
            jBoxFun.setSelectedIndex(-1);

            // 9. REABILITA CONFIRMAR APÓS ATUALIZAR
            jBConfirmar.setEnabled(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBAtualizarActionPerformed

    private void jBlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimparActionPerformed
        // LIMPA TODOS OS CAMPOS
        jTNomeFun.setText("");
        jTCPF.setText("");
        jTTelefone.setText("");
        jTEmailFun.setText("");
        jTSenha.setText("");
        jTCepFun.setText("");
        jTNumeroFun.setText("");
        jBoxFun.setSelectedIndex(-1);

        // REABILITA O BOTÃO CONFIRMAR
        jBConfirmar.setEnabled(true);

        // MENSAGEM NO CONSOLE (OPCIONAL)
        System.out.println("✓ Campos limpos!");
    }//GEN-LAST:event_jBlimparActionPerformed

    private void jBvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvoltarActionPerformed
        // Fecha a tela atual (Cadastro de Funcionário)
        this.dispose();

        // Abre a tela do Menu
        new Menu().setVisible(true);

        System.out.println("✓ Voltou para o menu principal");
    }//GEN-LAST:event_jBvoltarActionPerformed
    
    // MÉTODO PARA CARREGAR FUNCIONÁRIOS DO BANCO
    private void carregarTabelaFuncionarios() {
        try {
            // Limpa a tabela antes de carregar
            modelo.setRowCount(0);
            
            // Busca todos os funcionários do banco
            FuncionarioDAO dao = new FuncionarioDAO();
            java.util.List<Funcionario> funcionarios = dao.read();
            
            // Adiciona cada funcionário na tabela
            for (Funcionario f : funcionarios) {
                modelo.addRow(new Object[]{
                    f.getNome_Fun(),
                    f.getCpf(),
                    f.getTelefone_Fun(),
                    f.getEmail_Fun(),
                    f.getFuncao()
                });
            }
            
            System.out.println("✓ " + funcionarios.size() + " funcionário(s) carregado(s)!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar funcionários: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaCadastroFun().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBlimpar;
    private javax.swing.JComboBox<String> jBoxFun;
    private javax.swing.JButton jBvoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCPF;
    private javax.swing.JTextField jTCepFun;
    private javax.swing.JTextField jTEmailFun;
    private javax.swing.JTextField jTNomeFun;
    private javax.swing.JTextField jTNumeroFun;
    private javax.swing.JTextField jTSenha;
    private javax.swing.JTable jTTable1;
    private javax.swing.JTextField jTTelefone;
    // End of variables declaration//GEN-END:variables

}